### ISSUE TITLE
Current day border should represent overall day score, rather than completion progress

### ISSUE THREAD

**Issue by BattleDog249** [Healthy-Habits-project/healthy-habits#4]
The border on each page changes color based on the average completion of each of the four health pages for that day. For example, if all four of the pages are completed, the individual health bars will all be full, and the border dark green. However, in this scenario, the day score is not visible unless the user clicks on another day, which hides the individual health bars of the current day.
I propose that the border should be set to the color of the score the user selects for that day, so the average score can be determined even when the background is covered by progress bars, or simply remove the border color to avoid confusion.
Not a major priority.

**Comment by Pupo-Professional** [comment]
Can be done, 
          cellStyle.backgroundColor = ratingColor;
          cellStyle.border = `4px solid ${ratingColor}`; 
          
          Passing the rating color to the style of the cells border.
